# Load & Combine All Data

In [ ]:
import pandas as pd
import numpy as np
import os

# Combine all horse data and save it to a single file
horse_files_path = "D:\\Programming\\GUVI PROJECTS CODE\\Horse Race Prediction\\Project Info\\Horces"
race_files_path = "D:\\Programming\\GUVI PROJECTS CODE\\Horse Race Prediction\\Project Info\\Races"
all_horse_data = []
all_race_data = []

if os.path.exists(horse_files_path) and os.path.exists(race_files_path):
    for file in os.listdir(horse_files_path):
        if file.endswith(".csv"):
            horse_data = os.path.join(horse_files_path, file)
            horse_df = pd.read_csv(horse_data)
            horse_df['Year'] = file.split(".")[0].split("_")[1] # Add year to the data
            all_horse_data.append(horse_df)
    
    for file in os.listdir(race_files_path):
        if file.endswith(".csv"):
            race_data = os.path.join(race_files_path, file)
            race_df = pd.read_csv(race_data)
            race_df['Year'] = file.split(".")[0].split("_")[1] # Add year to the data
            all_race_data.append(race_df)

    combined_horse_data = pd.concat(all_horse_data, ignore_index=True)
    combined_race_data = pd.concat(all_race_data, ignore_index=True)

else:
    print(f"Directory {horse_files_path} does not exist.")
    print(f"Directory {race_files_path} does not exist.")

In [2]:
horse_df = combined_horse_data
race_df = combined_race_data

# Removing Missing Values

For horse_df

In [3]:
missing_threshold = 0.5  # set the threshold for missing values

# 1. Remove columns with more than 50% of missing values
missing_percentage = horse_df.isnull().mean()
columns_to_drop = missing_percentage[missing_percentage > missing_threshold].index
horse_df.drop(columns=columns_to_drop, inplace=True)
print(f"Columns with more than 50% missing values: {columns_to_drop}")

Columns with more than 50% missing values: Index(['overWeight', 'outHandicap', 'headGear', 'price'], dtype='object')

For race_df

In [4]:
missing_threshold = 0.5  # set the threshold for missing values

# 1. Remove columns with more than 50% of missing values
missing_percentage = race_df.isnull().mean()
columns_to_drop = missing_percentage[missing_percentage > missing_threshold].index
race_df.drop(columns=columns_to_drop, inplace=True)
print(f"Columns with more than 50% missing values: {columns_to_drop}")

Columns with more than 50% missing values: Index(['band', 'hurdles', 'currency'], dtype='object')

Drop Duplicate Columns

In [5]:
horse_df.drop_duplicates(inplace=True)
race_df.drop_duplicates(inplace=True)

In [6]:
print(f"Shape of horse data: {horse_df.shape}")
print(f"Shape of race data: {race_df.shape}")

Shape of horse data: (4107315, 25)
Shape of race data: (396572, 17)

# Changing Datatypes

### For Horse Data

In [7]:
horse_df['rid'] = horse_df['rid'].astype('category')
horse_df['horseName'] = horse_df['horseName'].astype('category')
horse_df['age'] = horse_df['age'].astype('category')
horse_df['saddle'] = horse_df['saddle'].astype('category')
horse_df['decimalPrice'] = horse_df['decimalPrice'].astype('category')
horse_df['isFav'] = horse_df['isFav'].astype(bool)
horse_df['trainerName'] = horse_df['trainerName'].astype('category')    
horse_df['jockeyName'] = horse_df['jockeyName'].astype('category')
horse_df['position'] = horse_df['position'].astype('category')
horse_df['positionL'] = horse_df['positionL'].astype('category')
horse_df['dist'] = pd.to_numeric(horse_df['dist'], errors='coerce') 
horse_df['weightSt'] = horse_df['weightSt'].astype('category')
horse_df['weightLb'] = horse_df['weightLb'].astype('category')
horse_df['RPR'] = pd.to_numeric(horse_df['RPR'], errors='coerce')
horse_df['OR'] = pd.to_numeric(horse_df['OR'], errors='coerce')
horse_df['TR'] = pd.to_numeric(horse_df['TR'], errors='coerce')
horse_df['father'] = horse_df['father'].astype('category')
horse_df['mother'] = horse_df['mother'].astype('category')
horse_df['gfather'] = horse_df['gfather'].astype('category')
horse_df['runners'] = horse_df['runners'].astype('category')
horse_df['margin'] = pd.to_numeric(horse_df['margin'], errors='coerce')
horse_df['weight'] = pd.to_numeric(horse_df['weight'], errors='coerce')
horse_df['res_win'] = horse_df['res_win'].astype(bool)
horse_df['res_place'] = horse_df['res_place'].astype(bool)
horse_df['Year'] = pd.to_datetime(horse_df['Year'], format='%Y')

In [8]:
horse_df.dtypes

rid                   category
horseName             category
age                   category
saddle                category
decimalPrice          category
isFav                     bool
trainerName           category
jockeyName            category
position              category
positionL             category
dist                   float64
weightSt              category
weightLb              category
RPR                    float64
TR                     float64
OR                     float64
father                category
mother                category
gfather               category
runners               category
margin                 float64
weight                   int64
res_win                   bool
res_place                 bool
Year            datetime64[ns]
dtype: object

### For Race Data

In [9]:
race_df['rid'] = race_df['rid'].astype('category')
race_df['course'] = race_df['course'].astype('category')
race_df['time'] = pd.to_datetime(race_df['time'], format='%H:%M', errors='coerce')
race_df['date'] = pd.to_datetime(race_df['date'], format='%Y-%m-%d', errors='coerce')
race_df['title'] = race_df['title'].astype('category')
race_df['condition'] = race_df['condition'].astype('category')
race_df['total_prize'] = pd.to_numeric(race_df['prize'], errors='coerce')
race_df['countryCode'] = race_df['countryCode'].astype('category')
race_df['class'] = race_df['class'].astype('category')
race_df['Year'] = pd.to_datetime(race_df['Year'], format='%Y', errors='coerce')

Handle ages column

In [10]:
# Function to parse ages
def parse_age(age):
    if pd.isna(age):
        return {"min_age": np.nan, "max_age": np.nan}
    if '+' in age:
        min_age = int(age.replace('yo+', '').strip())
        return {"min_age": min_age, "max_age": 99}  # Assume 99 as cap
    if '-' in age:
        min_age, max_age = map(int, age.replace('yo', '').split('-'))
        return {"min_age": min_age, "max_age": max_age}
    else:
        min_age = int(age.replace('yo', '').strip())
        return {"min_age": min_age, "max_age": min_age}

# Apply the function and create new columns
age_parsed = race_df['ages'].apply(parse_age)
race_df['min_age'] = age_parsed.apply(lambda x: x['min_age'])
race_df['max_age'] = age_parsed.apply(lambda x: x['max_age'])

# Drop the original 'ages' column
race_df.drop(columns=['ages'], inplace=True)

Handle distance column

In [11]:
import re

# Function to parse distances into miles
def parse_distance_to_miles(dist):
    # Initialize
    miles, furlongs = 0, 0.0

    # Regex to extract miles and furlongs
    miles_match = re.search(r'(\d+)m', dist)
    furlongs_match = re.search(r'(\d+|\d+/\d+|½|¼)f', dist)

    # Parse miles
    if miles_match:
        miles = int(miles_match.group(1))

    # Parse furlongs
    if furlongs_match:
        furlongs_str = furlongs_match.group(1)
        if '½' in furlongs_str:
            furlongs = 0.5
        elif '¼' in furlongs_str:
            furlongs = 0.25
        elif '/' in furlongs_str:
            num, denom = map(int, furlongs_str.split('/'))
            furlongs = num / denom
        else:
            furlongs = int(furlongs_str)

    # Convert furlongs to miles
    miles += furlongs / 8
    return miles

race_df['distance'] = race_df['distance'].apply(parse_distance_to_miles)

Break prizes column

In [12]:
import pandas as pd
import ast  # For safely converting strings to lists

# Parse the prizes into lists
def parse_prizes(prizes_str):
    try:
        return ast.literal_eval(prizes_str)
    except (ValueError, SyntaxError):  # Handle parsing errors
        return []

# Apply parsing
race_df['prizes'] = race_df['prizes'].apply(parse_prizes)

# Find the maximum number of prizes in any row
max_prizes = race_df['prizes'].apply(len).max()

# Create new columns for each prize
for i in range(max_prizes):
    race_df[f'prize_{i+1}'] = race_df['prizes'].apply(lambda x: x[i] if i < len(x) else None)

race_df.drop(columns=['prizes'],inplace=True)    # Drop the intermediate parsed column if not needed

Drop Unnecessary Columns

In [13]:
race_df.drop(columns=['rclass'], inplace=True)
race_df.drop(columns=['prize'], inplace=True)
race_df.drop(columns=['ncond'], inplace=True)

In [14]:
for i in range(1, max_prizes+1):
    race_df[f'prize_{i}'] = race_df[f'prize_{i}'].fillna(0)

In [15]:
race_df.dtypes

rid                  category
course               category
time           datetime64[ns]
date           datetime64[ns]
title                category
distance              float64
condition            category
winningTime           float64
metric                float64
countryCode          category
class                category
Year           datetime64[ns]
total_prize           float64
min_age               float64
max_age               float64
prize_1               float64
prize_2               float64
prize_3               float64
prize_4               float64
prize_5               float64
prize_6               float64
prize_7               float64
prize_8               float64
prize_9               float64
prize_10              float64
prize_11              float64
prize_12              float64
prize_13              float64
prize_14              float64
prize_15              float64
prize_16              float64
prize_17              float64
prize_18              float64
dtype: object

# Combine horse_df and race_df into one dataframe

In [16]:
df = pd.merge(horse_df, race_df, on='rid', suffixes=('_horse', '_race'))    # Merge the two dataframes
df['rid'] = df['rid'].astype('category')        # Convert to category
df['weight'] = df['weight'].astype('category')  # Convert to category

In [17]:
df.head()

,rid,horseName,age,saddle,decimalPrice,isFav,trainerName,jockeyName,position,positionL,...,prize_9,prize_10,prize_11,prize_12,prize_13,prize_14,prize_15,prize_16,prize_17,prize_18
0,271018,Combermere,6.0,0.0,0.222222,False,R G Frost,J Frost,1,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,271018,Royal Battery,6.0,0.0,0.090909,False,D H Barons,S Earle,2,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,271018,Just So,7.0,0.0,0.029412,False,J D Roberts,S Burrough,3,15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,271018,Mandraki Shuffle,8.0,0.0,0.090909,False,Oliver Sherwood,M Richards,4,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,271018,Turnberry Dawn,8.0,0.0,0.047619,False,T B Hallett,P Richards,5,dist,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Handle Missing Values further

In [18]:
df.isnull().sum()

rid                   0
horseName             0
age                 309
saddle           179168
decimalPrice          0
isFav                 0
trainerName        2850
jockeyName          125
position              0
positionL        783662
dist            1077821
weightSt              0
weightLb              0
RPR              864877
TR              1681610
OR              1795263
father             1289
mother             4480
gfather          119374
runners               0
margin                0
weight                0
res_win               0
res_place             0
Year_horse            0
course                0
time                  0
date            4107315
title                 7
distance              0
condition           404
winningTime           0
metric                0
countryCode           0
class                 0
Year_race             0
total_prize      235284
min_age          143485
max_age          143485
prize_1               0
prize_2               0
prize_3               0
prize_4               0
prize_5               0
prize_6               0
prize_7               0
prize_8               0
prize_9               0
prize_10              0
prize_11              0
prize_12              0
prize_13              0
prize_14              0
prize_15              0
prize_16              0
prize_17              0
prize_18              0
dtype: int64

In [19]:
df.drop(columns=['date'], inplace=True)

In [20]:
# Replace missing values for all columns as required
df['age'] = df['age'].fillna(df['age'].mode()[0])
df['saddle'] = df['saddle'].fillna(df['saddle'].mode()[0])
df['trainerName'] = df['trainerName'].fillna(df['trainerName'].mode()[0])
df['jockeyName'] = df['jockeyName'].fillna(df['jockeyName'].mode()[0])
df['positionL'] = df['positionL'].fillna(df['positionL'].mode()[0])
df['dist'] = df['dist'].fillna(df['dist'].mean())
df['RPR'] = df['RPR'].fillna(df['RPR'].mean())
df['OR'] = df['OR'].fillna(df['OR'].mean())
df['TR'] = df['TR'].fillna(df['TR'].mean())
df['father'] = df['father'].fillna(df['father'].mode()[0])
df['mother'] = df['mother'].fillna(df['mother'].mode()[0])
df['gfather'] = df['gfather'].fillna(df['gfather'].mode()[0])
df['title'] = df['title'].fillna(df['title'].mode()[0])
df['condition'] = df['condition'].fillna(df['condition'].mode()[0])
df['total_prize'] = df['total_prize'].fillna(df['total_prize'].mean())
df['min_age'] = df['min_age'].fillna(df['min_age'].mean())
df['max_age'] = df['max_age'].fillna(df['max_age'].mean())

# Feature Selection

Chi Square Test

In [57]:
from scipy.stats import chi2_contingency

target1 = 'res_win'
target2 = 'res_place'

# Define the categorical columns
categorical_columns = df.select_dtypes(include=['category']).columns.to_list()
categorical_columns.remove('rid')  # Remove the 'rid' column

def chi_square_test(df, target):
    # Initialize a dictionary to store the p-values
    p_values = {}

    # Loop through each categorical column
    for column in categorical_columns:
        # Create a contingency table
        contingency_table = pd.crosstab(df[target], df[column])
        # Perform the chi-square test
        _, p_value, _, _ = chi2_contingency(contingency_table)
        # Store the p-value
        p_values[column] = p_value

    # Convert the p-values to a DataFrame for better visualization
    p_values_df = pd.Series(p_values, name='p-value').reset_index()
    p_values_df = p_values_df.rename(columns={'index': 'Column'})
    p_values_df['Significant'] = p_values_df['p-value'] < 0.05
    return p_values_df

# Perform the chi-square test for the 'res_win' target
p_values_win = chi_square_test(df, target1)
p_values_win

          Column        p-value  Significant
0      horseName   0.000000e+00         True
1            age   0.000000e+00         True
2         saddle   0.000000e+00         True
3   decimalPrice   0.000000e+00         True
4    trainerName   0.000000e+00         True
5     jockeyName   0.000000e+00         True
6       position   0.000000e+00         True
7      positionL   0.000000e+00         True
8       weightSt   0.000000e+00         True
9       weightLb  5.684092e-144         True
10        father   0.000000e+00         True
11        mother   0.000000e+00         True
12       gfather   0.000000e+00         True
13       runners   0.000000e+00         True
14        weight   0.000000e+00         True
15        course   0.000000e+00         True
16     condition   0.000000e+00         True
17   countryCode   0.000000e+00         True
18         class   0.000000e+00         True

In [58]:
# Drop the columns with p-value > 0.05
columns_to_drop = p_values_win[p_values_win['Significant'] == False]['Column'].values
df.drop(columns=columns_to_drop, inplace=True)

In [59]:
# perform the chi-square test for the 'res_place' target
p_values_place = chi_square_test(df, target2)
p_values_place

          Column        p-value  Significant
0      horseName   0.000000e+00         True
1            age   0.000000e+00         True
2         saddle   0.000000e+00         True
3   decimalPrice   0.000000e+00         True
4    trainerName   0.000000e+00         True
5     jockeyName   0.000000e+00         True
6       position   0.000000e+00         True
7      positionL   0.000000e+00         True
8       weightSt   0.000000e+00         True
9       weightLb  3.795061e-195         True
10        father   0.000000e+00         True
11        mother   0.000000e+00         True
12       gfather   0.000000e+00         True
13       runners   0.000000e+00         True
14        weight   0.000000e+00         True
15        course   0.000000e+00         True
16     condition   0.000000e+00         True
17   countryCode   0.000000e+00         True
18         class   0.000000e+00         True

In [60]:
# Drop the columns with p-value > 0.05
columns_to_drop = p_values_place[p_values_place['Significant'] == False]['Column'].values
# df.drop(columns=columns_to_drop, inplace=True)

ANOVA test for numerical columns

In [61]:
# ANOVA test for numerical columns
from scipy.stats import f_oneway

# Define the numerical columns
numerical_columns = df.select_dtypes(include=['float64']).columns

def anova_test(df, target):
    # Initialize a dictionary to store the p-values
    p_values = {}

    # Loop through each numerical column
    for column in numerical_columns:
        # Perform the ANOVA test
        _, p_value = f_oneway(df[df[target] == 0][column], df[df[target] == 1][column])
        # Store the p-value
        p_values[column] = p_value

    # Convert the p-values to a DataFrame for better visualization
    p_values_df = pd.Series(p_values, name='p-value').reset_index()
    p_values_df = p_values_df.rename(columns={'index': 'Column'})
    p_values_df['Significant'] = p_values_df['p-value'] < 0.05
    return p_values_df

# Perform the ANOVA test for the 'res_win' target
p_values_win_anova = anova_test(df, target1)
p_values_win_anova

         Column       p-value  Significant
0          dist  9.936524e-01        False
1           RPR  0.000000e+00         True
2            TR  0.000000e+00         True
3            OR  0.000000e+00         True
4        margin  0.000000e+00         True
5      distance  1.420347e-10         True
6   winningTime  2.334997e-25         True
7        metric  1.057212e-19         True
8   total_prize  5.076762e-44         True
9       min_age  6.298539e-01        False
10      max_age  1.374089e-13         True
11      prize_1  7.230087e-37         True
12      prize_2  1.413295e-36         True
13      prize_3  1.293965e-39         True
14      prize_4  8.495832e-39         True
15      prize_5  2.960526e-43         True
16      prize_6  9.656688e-13         True
17      prize_7  4.268885e-08         True
18      prize_8  1.074716e-07         True
19      prize_9  1.737065e-04         True
20     prize_10  1.967602e-04         True
21     prize_11  2.862953e-01        False
22     prize_12  3.031779e-01        False
23     prize_13  1.980111e-03         True
24     prize_14  3.338581e-03         True
25     prize_15  1.487601e-02         True
26     prize_16  2.012990e-02         True
27     prize_17  4.698316e-02         True
28     prize_18  1.091095e-01        False

In [64]:
# Drop the columns with p-value > 0.05
columns_to_drop = p_values_win_anova[p_values_win_anova['Significant'] == False]['Column'].values
df.drop(columns=columns_to_drop, inplace=True)

In [67]:
# Perform the ANOVA test for the 'res_place' target
p_values_place_anova = anova_test(df, target2)
p_values_place_anova

KeyError: 'dist'

In [ ]:
# Drop the columns with p-value > 0.05
columns_to_drop = p_values_place_anova[p_values_place_anova['Significant'] == False]['Column'].values

KeyError: "['prize_11', 'prize_12', 'prize_18'] not found in axis"

# Encoding Categorical Columns

In [24]:
categorical_columns = df.select_dtypes(include=['category']).columns

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

df.head()

In [ ]:
df.select_dtypes(include=['object']).columns

In [28]:
import pickle

# Save the label encoders
with open('label_encoders.pkl', 'wb') as f:
    pickle.dump(label_encoders, f)

In [29]:
df.to_csv('combined_data.csv', index=False)     # Save the combined data to a file